version: "3"

name: memechose

# for communication with other services in the future
networks:
  memechose:
    external: true

services:
  db:
    container_name: db
    build: ./postgresql
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgresql/sql-scripts:/docker-entrypoint-initdb.d/
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    networks:
      memechose:
        aliases:
          - postgres

  api:
    container_name: api
    build:
      dockerfile: ./api/Dockerfile
      context: ./
    restart: always
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/api
    env_file:
      - .env
    networks:
      memechose:
        aliases:
          - memechose
          - django
