# Generated by Django 4.1.5 on 2023-01-05 18:50

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "short",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                (
                    "long",
                    models.CharField(max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "time_to_live",
                    models.DurationField(default=api.models.DEFAULT_TTL_TIMEDELTA),
                ),
                (
                    "hits",
                    models.BigIntegerField(default=0),
                ),
            ],
        ),
    ]
